In [1]:
# Imports
from dotenv import load_dotenv
import pyfabricops as pf
import os
from pathlib import Path


# Setups
pf.set_auth_provider('env')
pf.setup_logging(format_style='minimal', level='info')

In [2]:
# Find root path
def find_root_path(
    start: Path = None,
    markers: list[str] = None
) -> Path:
    start = (start or Path.cwd()).resolve()
    markers = markers or [
        ".git",         
        ".gitignore",
    ]
    for directory in [start, *start.parents]:
        for m in markers:
            if (directory / m).exists():
                return directory
    return start

root_path = find_root_path()
print(f"Root path: {root_path}")

Root path: C:\repos\pyfabricops-demo-002-fabric

In [3]:
# Capture git info
branches_path = Path(root_path) / 'branches.json'
branch = pf.get_current_branch()
workspace_suffix = pf.get_workspace_suffix(branch, path = branches_path) 
print('Branch:', branch, 'Workspace Suffix:', workspace_suffix)

Branch: main Workspace Suffix: -PRD

In [4]:
# Project config
project = 'PF_002_Fabric'
project_path = Path(root_path)/'src'
workspace_alias ='PF_002_Fabric'
workspace_name = workspace_alias + workspace_suffix
capacity = '7732a1eb-3893-4642-a85c-93fc3f35d076' 
print('Workspace name: ', workspace_name)

Workspace name:  PF_002_Fabric-PRD

In [5]:
workspaces_roles_path = Path(root_path) / 'workspaces_roles.json'
roles = pf.read_json(workspaces_roles_path) 
display(pf.json_to_df(roles))

                              user_uuid         user_type   role
0  9322eb4a-4132-4bd1-8df1-5cd3d1d2400b              User  Admin
1  b025341a-965a-4c35-b12e-2af63e5eb58f              User  Admin
2  bde43861-55e1-4144-b572-be115312967f  ServicePrincipal  Admin

In [8]:
# Create the workspace

pf.create_workspace(
    workspace_name,
    description='CI/CD with Microsoft Fabric and PyFabricOps',
    capacity=capacity,
    roles=roles,
    df=True,
)

✓ User "9322eb4a-4132-4bd1-8df1-5cd3d1d2400b", type "User" with role "Admin" was added to workspace d094d273-5051-458b-b76a-c300084189df successfully.
✓ User "b025341a-965a-4c35-b12e-2af63e5eb58f", type "User" with role "Admin" was added to workspace d094d273-5051-458b-b76a-c300084189df successfully.
△ 409: {"requestId":"201ec49c-9161-4556-b431-32c41959b4e4","errorCode":"PrincipalAlreadyHasWorkspaceRolePermissions","moreDetails":[{"relatedResource":{"resourceId":"bde43861-55e1-4144-b572-be115312967f","resourceType":"Principal"}}],"message":"The provided principal already has a role assigned in the workspace","relatedResource":{"resourceId":"d094d273-5051-458b-b76a-c300084189df","resourceType":"Workspace"}}.

,id,displayName,description,type,capacityId,capacityRegion,oneLakeEndpoints_blobEndpoint,oneLakeEndpoints_dfsEndpoint,capacityAssignmentProgress
0,d094d273-5051-458b-b76a-c300084189df,PF_002_Fabric-PRD,CI/CD with Microsoft Fabric and PyFabricOps,Workspace,7732a1eb-3893-4642-a85c-93fc3f35d076,East US,https://eastus-onelake.blob.fabric.microsoft.com,https://eastus-onelake.dfs.fabric.microsoft.com,Completed

In [9]:
# Create project
pf.export_workspace_config(
    workspace_name,
    project_path,
    branches_path=branches_path,
    workspace_suffix=workspace_suffix
)

i Found existing config file at C:\repos\pyfabricops-demo-002-fabric\src\config.json, merging workspace config...
✓ Updated workspace_config for "PF_002_Fabric" in branch "main"
✓ Workspace configuration successfully written to C:\repos\pyfabricops-demo-002-fabric\src\config.json

In [15]:
# Create `storage` folder
storage_folder = pf.create_folder(
    workspace_name,
    'Storage',
)
storage_folder_id = storage_folder['id'] 
display(pf.json_to_df(storage_folder))
print('Folder `storage` created with id: ', storage_folder_id)

,id,displayName,workspaceId
0,5f41eb9d-97cb-4757-9375-87113cf086aa,Storage,d094d273-5051-458b-b76a-c300084189df

Folder `storage` created with id:  5f41eb9d-97cb-4757-9375-87113cf086aa

In [16]:
# Create `Orchestration` folder
orchestration_folder = pf.create_folder(
    workspace_name,
    'Orchestration',
)
orchestration_folder_id = orchestration_folder['id'] 
display(pf.json_to_df(orchestration_folder))
print('Folder `Orchestration` created with id: ', orchestration_folder_id)

,id,displayName,workspaceId
0,f0498c71-1d14-4ef3-822e-cc6680d0d8d8,Orchestration,d094d273-5051-458b-b76a-c300084189df

Folder `Orchestration` created with id:  f0498c71-1d14-4ef3-822e-cc6680d0d8d8

In [17]:
# Create `PowerBI` folder
powerbi_folder = pf.create_folder(
    workspace_name,
    'PowerBI',
)
powerbi_folder_id = powerbi_folder['id'] 
display(pf.json_to_df(powerbi_folder))
print('Folder `PowerBI` created with id: ', powerbi_folder_id)

,id,displayName,workspaceId
0,6639ff55-af99-4068-97eb-a8f2155b4f39,PowerBI,d094d273-5051-458b-b76a-c300084189df

Folder `PowerBI` created with id:  6639ff55-af99-4068-97eb-a8f2155b4f39

In [18]:
# Create subfolders `DirectLake` and `Import` 
subfolders = ['DirectLake', 'Import']
parent_folder_id = powerbi_folder_id 
for subfolder in subfolders:
    subfolder_created = pf.create_folder(
        workspace_name, 
        subfolder, 
        parent_folder=powerbi_folder_id,
    )
    subfolder_created_id = subfolder_created['id']
    print(f'Folder `{subfolder}` created with id: {subfolder_created_id} under `PowerBI`')

Folder `DirectLake` created with id: ced8691d-7bfe-4b95-8aeb-ba49e92f0cc2 under `PowerBI`
Folder `Import` created with id: 03bd2158-899b-4a01-8027-b9a02ea1195f under `PowerBI`

In [19]:
# Create OtherAnalysis folder
other_analysis_folder = pf.create_folder(
    workspace_name,
    'OtherAnalysis',
    parent_folder='Import'
)
other_analysis_folder_id = other_analysis_folder['id']
print(f'Folder `OtherAnalysis` created with id: {other_analysis_folder_id} under `PowerBI/Import`')

Folder `OtherAnalysis` created with id: d2e4f78a-c002-42c5-be38-e94eb2829559 under `PowerBI/Import`

In [20]:
# Export folders to config
pf.export_folders(
    workspace_name,
    project_path,
    branches_path=branches_path,
    workspace_suffix=workspace_suffix
)

✓ Folder structure created at C:/repos/pyfabricops-demo-002-fabric/src/PF_002_Fabric
✓ Updated folders config for workspace "PF_002_Fabric" in branch "main"
✓ Folders configuration successfully written to C:\repos\pyfabricops-demo-002-fabric\src\config.json.

In [21]:
# Load config
config_path = Path(project_path)/'config.json'
config = pf.read_json(config_path)

In [22]:
workspace_id = config[branch][workspace_alias]['workspace_config']['workspace_id']

In [ ]:
workspace_id = config[branch][workspace_alias]['workspace_config']['workspace_id']
storage_folder_id_c = config[branch][workspace_alias]['folders']['Storage']

In [ ]:
# Create lakehouse
pf.create_lakehouse(
    workspace_id,
    'MainStorage', 
    description='The main storage of the lakehouse',  
    folder=storage_folder_id_c,
    df=True
)

In [ ]:
# Export lakehouse to config
pf.export_lakehouse(
    workspace_id,
    'MainStorage',
    project_path,
    workspace_path=workspace_alias,
    branches_path=branches_path,
    workspace_suffix=workspace_suffix,
)

In [23]:
# Create GitHub connection
load_dotenv() 
github_token = os.getenv('GH_TOKEN') 

github_connection = pf.create_github_source_control_connection(
    'PF_002_Fabric',
    'https://github.com/alisonpezzott/pyfabricops-demo-002-fabric',
    github_token,
) 

if github_connection:
    github_connection_id = github_connection['id']
else:
    github_connection_id = pf.get_connection('PF_002_Fabric')['id'] 

print('GitHub Connection: ', github_connection_id)

△ 400: {"requestId":"c9a2d9c6-66ff-4cf2-bf6b-7ce1bb6c3bac","errorCode":"InvalidInput","moreDetails":[{"errorCode":"InvalidParameter","message":"The Key field is required."}],"message":"The request has an invalid input"}.
GitHub Connection:  3c94d309-56aa-4be7-82a1-2bde73b54d78

In [24]:
connections_roles_path = Path(root_path) / 'connections_roles.json'
connections_roles = pf.read_json(connections_roles_path) 
display(pf.json_to_df(connections_roles))

                              user_uuid user_type             role
0  9322eb4a-4132-4bd1-8df1-5cd3d1d2400b      User            Owner
1  b025341a-965a-4c35-b12e-2af63e5eb58f      User             User
2  cbe83b10-3b7c-4479-8168-e5281fabf7ea     Group  UserWithReshare

In [25]:
# Add roles to connection
roles_added = []
for role in connections_roles:
    role_added = pf.add_connection_role_assignment(
        github_connection_id, 
        role['user_uuid'], 
        role['user_type'], 
        role['role']
    )
    if role_added:
        roles_added.append(role_added)

if roles_added:
    print('Added roles')
    display(pf.json_to_df(roles_added)) 
else:
    print('Current roles')
    current_connection_roles = pf.list_connection_role_assignments(github_connection_id, df=True) 
    display(current_connection_roles)

△ 409: {"requestId":"41be6052-e677-4be3-babe-105ac0f4c323","errorCode":"ConnectionRoleAssignmentAlreadyExists","moreDetails":[{"relatedResource":{"resourceId":"9322eb4a-4132-4bd1-8df1-5cd3d1d2400b","resourceType":"Principal"}}],"message":"Connection role assignment already exists","relatedResource":{"resourceId":"3c94d309-56aa-4be7-82a1-2bde73b54d78","resourceType":"Connection"}}.
△ 409: {"requestId":"34ca6a63-9716-40f8-ab48-248281e49014","errorCode":"ConnectionRoleAssignmentAlreadyExists","moreDetails":[{"relatedResource":{"resourceId":"b025341a-965a-4c35-b12e-2af63e5eb58f","resourceType":"Principal"}}],"message":"Connection role assignment already exists","relatedResource":{"resourceId":"3c94d309-56aa-4be7-82a1-2bde73b54d78","resourceType":"Connection"}}.
△ 409: {"requestId":"9f16fb35-882b-4d47-b727-857ea0699c08","errorCode":"ConnectionRoleAssignmentAlreadyExists","moreDetails":[{"relatedResource":{"resourceId":"cbe83b10-3b7c-4479-8168-e5281fabf7ea","resourceType":"Principal"}}],"message":"Connection role assignment already exists","relatedResource":{"resourceId":"3c94d309-56aa-4be7-82a1-2bde73b54d78","resourceType":"Connection"}}.
Current roles

,id,principal_id,principal_type,role
0,9322eb4a-4132-4bd1-8df1-5cd3d1d2400b,9322eb4a-4132-4bd1-8df1-5cd3d1d2400b,User,Owner
1,b025341a-965a-4c35-b12e-2af63e5eb58f,b025341a-965a-4c35-b12e-2af63e5eb58f,User,User
2,bde43861-55e1-4144-b572-be115312967f,bde43861-55e1-4144-b572-be115312967f,User,Owner
3,cbe83b10-3b7c-4479-8168-e5281fabf7ea,cbe83b10-3b7c-4479-8168-e5281fabf7ea,Group,UserWithReshare

In [26]:
# Connect workspace to git repository
pf.github_connect(
    workspace_id,
    github_connection_id,
    owner_name='alisonpezzott',
    repository_name='pyfabricops-demo-002-fabric',
    branch_name=branch,
    directory_name='src/' + workspace_alias
)

✓ Successfully connected GitHub repository 'pyfabricops-demo-002-fabric' to workspace 'd094d273-5051-458b-b76a-c300084189df'.

True

In [31]:
pf.update_my_git_connection(
    workspace_id,
    credential_type='spn',
    request_body_type='UpdateGitCredentialsToConfiguredConnectionRequest',
    connection_id='3c94d309-56aa-4be7-82a1-2bde73b54d78'
)

{'connectionId': '3c94d309-56aa-4be7-82a1-2bde73b54d78',
 'source': 'ConfiguredConnection'}

In [27]:
# Init Git
pf.git_init(workspace_id)

✓ Successfully initialized Git connection for workspace.

{'requiredAction': 'UpdateFromGit',
 'workspaceHead': None,
 'remoteCommitHash': 'c2f133a74681034bcfcd508f0b18e2a1c2525cff'}

In [32]:
# Check status beetwen workspace and git
changes = pf.git_status(workspace_id, credential_type='spn')
display(pf.json_to_df(changes['changes']))

i Successfully Git status retrieved for workspace.

,remoteChange,workspaceChange,conflictType,itemMetadata_itemIdentifier_logicalId,itemMetadata_itemType,itemMetadata_displayName
0,Added,None,None,6d841cc5-796e-9726-4a35-3b670f511484,Pipeline,CopyDataFromDB
1,Added,None,None,45b83078-1e62-897e-4c54-0da4852db475,SynapseNotebook,TransformAndLoad
2,Added,None,None,fdcc712f-aee7-47fa-bdbc-6a3729fd4c70,report,SalesAnalysis
3,Added,None,None,2a2e8773-ef8c-bd71-42dd-8e08db79b22f,dataset,SalesAnalysis
4,Added,None,None,3ea220ee-5d9a-4f6f-8ec3-2fc5b8925420,report,CustomersAnalysis
5,Added,None,None,b87f305e-32ee-4606-9b69-42f8f6e8ccc3,dataset,CustomersAnalysis
6,Added,None,None,e8b7c2f1-4a6d-4b9e-9e2a-3c7f2d8a1b5c,report,OtherAnalysis
7,Added,None,None,73da9bc7-5e09-4c2b-a36d-37f6ccd41738,Lakehouse,MainStorage